AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'bin/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/devise.rb'
    - 'config/initializers/backtrace_silencers.rb'
  UseCache: false
  TargetRailsVersion: 5.1
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario']
Documentation:
  Enabled: false
SymbolArray:
  Enabled: false
